spring:
  data:
    mongodb:
      uri: your-uri
      database: your-database-name 
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email 
    password: your-app-password 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
