spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: task_management_db
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dholakiya225@gmail.com
    password: znea cnoc nyqy zvqt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true